-- 오라클 6일차 오라클 객체 시퀸스(SEQUENCE)
-- 순차적으로 정수 값을 자동으로 생성한는 객체, 자동 번호 발생기(채번기)의 역할을 함
-- CREATE SEQUENCE [시퀀스명]; - 기본값으로 생성
-- CREATE SEQUENCE [시퀸스명] [시퀸스 옵션];
-- MINVALUE / MAXVALUE / START WITH : 처음 발생시킬 시작 값 기본1
-- INCREMENT BY : 다음 값 증가치 기본1 / NOCYCLE : 시퀸스가 최대값에 도달하면 START WITH로 재시작
-- NOCACHE : 메모리상에서 시퀸스값 관리, 기본20 시퀸스객체의 접근빈도를 줄여 효율적인 운영 가능
-- =================시퀀스 사용법============
-- 1. 시퀀스명.NEXTVAL : 최초로 호출한 후 사용해야함
-- 2. 시퀀스명.CURRVAL : 현재 LAST_NUMBER를 알려줌. (NEXTVAL을 1번이상 한 후 사용가능)
CREATE SEQUENCE SEQ_KH_MEMBER_NO;
SELECT * FROM USER_SEQUENCES;
SELECT SEQ_KH_MEMBER_NO.NEXTVAL FROM DUAL;
SELECT SEQ_KH_MEMBER_NO.CURRVAL FROM DUAL;
CREATE TABLE SEQUENCE_TBL
(
    NUM NUMBER PRIMARY KEY,
    NAME VARCHAR2(20) NOT NULL,
    AGE NUMBER NOT NULL
);
SELECT * FROM SEQUENCE_TBL;
INSERT INTO SEQUENCE_TBL
VALUES(SEQ_USER_NO.NEXTVAL, '일용자','31');
INSERT INTO SEQUENCE_TBL
VALUES(SEQ_USER_NO.NEXTVAL, '이용자','32');
INSERT INTO SEQUENCE_TBL
VALUES(SEQ_USER_NO.NEXTVAL, '삼용자','33');
ROLLBACK;
CREATE SEQUENCE SEQ_USER_NO;
SELECT * FROM USER_SEQUENCES;

-- @실습문제1
-- 고객이 상품주문시 사용할 테이블 ORDER_TBL 을 만들고, 다음과 같이 컬럼을 구성하세요
-- ORDER_NO(주문NO) : PK
-- USER_ID(고객아이디)
-- PRODUCT_ID(주문상품 아이디)
-- PRODECT_CNT(주문갯수)
-- ORDER_DATE : DEFAULT SYSDATE
CREATE TABLE ORDER_TBL
(
    ORDER_NO NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(40),
    PRODUCT_ID VARCHAR2(40),
    PRODUCT_CNT NUMBER,
    ORDER_DATE DATE DEFAULT SYSDATE
);
COMMENT ON COLUMN ORDER_TBL.ORDER_NO IS '주문NO';
COMMENT ON COLUMN ORDER_TBL.USER_ID IS '고객아이디';
COMMENT ON COLUMN ORDER_TBL.PRODUCT_ID IS '주문상품 아이디';
COMMENT ON COLUMN ORDER_TBL.PRODUCT_CNT IS '주문갯수';
COMMENT ON COLUMN ORDER_TBL.ORDER_DATE IS '주문날짜';
-- SEQ_ORDER_NO 시퀀스를 생성하여 다음의 테이터를 추가하세요
-- * kang님이 saewookkang상품을 5개 주문하셨습니다.
-- * gam님이 gamjakkang상품을 30개 주문하셨습니다.
-- * ring님이 onionring상품을 50개 주문하셨습니다.
CREATE SEQUENCE SEQ_ORDER_NO;
INSERT INTO ORDER_TBL
VALUES(SEQ_ORDER_NO.NEXTVAL, 'kang','saewookkang', 5, DEFAULT);
INSERT INTO ORDER_TBL
VALUES(SEQ_ORDER_NO.NEXTVAL, 'gam','gamjakkang', 30, DEFAULT);
INSERT INTO ORDER_TBL
VALUES(SEQ_ORDER_NO.NEXTVAL, 'ring','onionring', 50, DEFAULT);
CREATE TABLE ORDER_NEW_TBL
(
    ORDER_NO VARCHAR2(30) CONSTRAINT PK_ORDER_NO PRIMARY KEY,
    USER_ID VARCHAR2(40) NOT NULL,
    PRODUCT_ID VARCHAR2(40) NOT NULL,
    PRODUCT_CNT NUMBER(3),
    ORDER_DATE DATE DEFAULT SYSDATE
);
CREATE SEQUENCE SEQ_NEW_ORDER_NO;
INSERT INTO ORDER_NEW_TBL
VALUES('kh-'|| TO_CHAR(SYSDATE, 'yyyymmdd')||'-'||SEQ_NEW_ORDER_NO.NEXTVAL,'kang','saewookkang', 5, DEFAULT);
INSERT INTO ORDER_NEW_TBL
VALUES('kh-'|| TO_CHAR(SYSDATE, 'yyyymmdd')||'-'||SEQ_NEW_ORDER_NO.NEXTVAL,'gam','gamjakkang', 30, DEFAULT);
INSERT INTO ORDER_NEW_TBL
VALUES('kh-'|| TO_CHAR(SYSDATE, 'yyyymmdd')||'-'||SEQ_NEW_ORDER_NO.NEXTVAL,'ring','onionring', 50, DEFAULT);

-- @실습문제2
-- KH_MEMBER 테이블을 생성하세요
-- 컬럼 : MEMBER_ID, MEMVER_NAME, MEMBER_AGE, MEMBER_JOIN_COM
-- 자료형 : NUMBER, VARCHAR2(20), NUMBER, NUMBER
-- MEMBER_ID    MEMBER_NAME MEMBER_AGE  MEMBER_JOIN_COM
-- 500          홍길동      20          1
-- 510          청길동      30          2
-- 520          외길동      40          3
-- 530          고길동      50          4
CREATE TABLE KH_MEMBER
(
    MEMBER_ID NUMBER,
    MEMVER_NAME VARCHAR2(20),
    MEMBER_AGE NUMBER,
    MEMBER_JOIN_COM NUMBER
);
CREATE SEQUENCE SEQ_MEMBER_JOIN_COM;
CREATE SEQUENCE SEQ_MEMBER_ID START WITH 500 INCREMENT BY 10;
INSERT INTO KH_MEMBER
VALUES(SEQ_MEMBER_ID.NEXTVAL, '홍길동', 20, SEQ_MEMBER_JOIN_COM.NEXTVAL);
INSERT INTO KH_MEMBER
VALUES(SEQ_MEMBER_ID.NEXTVAL, '청길동', 30, SEQ_MEMBER_JOIN_COM.NEXTVAL);
INSERT INTO KH_MEMBER
VALUES(SEQ_MEMBER_ID.NEXTVAL, '외길동', 40, SEQ_MEMBER_JOIN_COM.NEXTVAL);
INSERT INTO KH_MEMBER
VALUES(SEQ_MEMBER_ID.NEXTVAL, '고길동', 50, SEQ_MEMBER_JOIN_COM.NEXTVAL);
-- DROP TABLE KH_MEMBER;
-- DROP SEQUENCE SEQ_MEMBER_JOIN_COM;
-- DROP SEQUENCE SEQ_MEMBER_ID;
ALTER SEQUENCE SEQ_MEMBER_ID
