SET SERVEROUTPUT ON;
--오라클 9일차 트리거 후반부
--트리거란?
--방아쇠, 연쇄반응
--회원을 삭제 후 삭제한 회원정보를 저장 (DELETE -> INSERT)
--DELETE가 되면은 자동으로 INSERT되도록 하는 것이 트리거
--예제로 INSERT ->신입사원이 입사하였습니다 메시지 출력
--INSERT가 되면은 자동으로 신입사원이 입사하였습니다 메시지 출력
--======================== 의사코드 OLD, NEW=========================
--FOR EACH ROW를 사용 (적어야 함)
--1.INSERT: OLD ->NULL(아무것도 없음),NEW -> 변경 후의 레코드 (INSERT된 정보)
--2.UPDATE:
--3.DELETE

-- 예제2. EMP_DUPLICATE 테이블에 정보를 삭제하였을 때, EMP_TEMP 라는 테이블에 삭제한 데이터의
-- 정보를 저장하는 트리거를 생성하시오. 단 트리거 이름은 TRG_EMP_DEL_INFO 라고 함.
-- 1. EMP_TEMP 테이블을 만드는 방법

CREATE TABLE EMP_TEMP
AS SELECT * FROM EMP_DUPLICATE WHERE 1 = 2;
SELECT * FROM EMP_TEMP;

CREATE OR REPLACE TRIGGER TRG_EMP_DEL_INFO
AFTER
DELETE ON EMP_DUPLICATE
FOR EACH ROW
BEGIN
    INSERT INTO EMP_TEMP
    VALUES(:OLD.EMP_ID, :OLD.EMP_NAME, :OLD.EMP_NO, :OLD.EMAIL, :OLD.PHONE, :OLD.DEPT_CODE, :OLD.JOB_CODE, :OLD.SAL_LEVEL, :OLD.SALARY, :OLD.BONUS, :OLD.MANAGER_ID
    , :OLD.HIRE_DATE, :OLD.ENT_DATE, :OLD.ENT_YN);
END;
/
-- 3. 트리거 생성 확인 후 테스트 해봄
COMMIT;
DELETE FROM EMP_DUPLICATE WHERE EMP_ID = '201';
SELECT * FROM EMP_TEMP;
SELECT * FROM EMP_DUPLICATE;
-- 실습 1
-- 1. 제품 PRODUCT 테이블블은 숫자로 된 PCODE 컬럼이 있고 PRIMARRY KEY로 지정한다
-- 문자열 크기가 30인 PNAME인 컬럼, 문자열 크기가 30인 BRAND컬럼, 숫자로 된 PRICE 컬럼
-- 숫자로 되어 있고 기본값이 0인 STOCK 컬럼이 있음
CREATE TABLE PRODUCT
(
    PCODE NUMBER PRIMARY KEY,
    PNAME VARCHAR2(30),
    BRAND VARCHAR2(30),
    PRICE NUMBER,
    STOCK NUMBER DEFAULT 0
);
SELECT * FROM PRODUCT;
-- 2. 제품 입출고 PRODUCT_IO 테이블은 숫자로 된 IOCODE 컬럼이 있고 PRIMARY KEY 로 지정한다.
-- 숫자로 된 PCODE 컬럼, 날짜로 된 PDATE 컬럼 숫자로 된 AMOUNT 컬럼, 문자열 크기가 10인
-- STATUS 컬럼이 있음 STATUS 컬럼은 입고 또는 출고만 입력가능함
-- PCODE 는 PRODUCT 테이블의 PCODE를 참조하여 외래키로 설정한다.
CREATE TABLE PRODUCT_IO
(
    IOCODE NUMBER PRIMARY KEY,
    PCODE NUMBER, -- 컬럼 레벨 CONSTRAINT FK_PRODUCT_IO REFERENCES PRODCUT (PCODE)
    PDATE DATE,
    AMOUNT NUMBER,
    STATUS VARCHAR2(10) CHECK(STATUS IN('입고','출고'))
    -- 테이블 레벨, FOREIGN KEY(PCODE) REFERENCES PRODUCT(PCODE)
);
SELECT * FROM PRODUCT_IO;
-- ***** 외래키 설정변경
ALTER TABLE PRODUCT_IO
ADD CONSTRAINT FK_PRODUCT_IO FOREIGN KEY(PCODE) REFERENCES PRODUCT(PCODE);
-- 3. 시퀸스는 SEQ_PRODUCT_PCODE, SEQ_PRODUVTIO_IOCODE라는 이름으로 기본값으로 설정되어 있음
CREATE SEQUENCE SEQ_PRODUCT_PCODE
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;
CREATE SEQUENCE SEQ_PRODUCT_IOCODE;
-- 4. 트리거의 이름은 TRG_PRODUCT 이고 PRODUCT_IO 테이블에 입고를 하면 PRODUCT 테이블에
-- STOCK컬럼에 값을 추가하고 PRODUCT_IO 테이블에 출고를 하면 STOCK 컬럼에 값을 빼주어야 한다.
INSERT INTO PRODUCT 
VALUES(SEQ_PRODUCT_PCODE.NEXTVAL, '농구공', 'NBA', '20000', DEFAULT);
DESC PRODUCT_IO;

INSERT INTO PRODUCT_IO 
VALUES(SEQ_PRODUCT_IOCODE.NEXTVAL, 1, SYSDATE, 10, '입고');
INSERT INTO PRODUCT_IO
VALUES(SEQ_PRODUCT_PCODE.NEXTVAL, 1, SYSDATE, 5, '출고');
COMMIT;

CREATE OR REPLACE TRIGGER TRG_PRODUCT -- INSERT 후 동작해야 되는 쿼리문
AFTER INSERT ON PRODUCT_IO
FOR EACH ROW
BEGIN
    IF (:NEW.STATUS = '입고') THEN 
        UPDATE PRODUCT  
        SET STOCK = STOCK + :NEW.AMOUNT
        WHERE PCODE = :NEW.PCODE;
    ELSIF (:NEW.STATUS = '출고') THEN
        UPDATE PRODUCT
        SET STOCK = STOCK - :NEW.AMOUNT
        WHERE PCODE = :NEW.PCODE;
    END IF;
END;
/
SELECT * FROM PRODUCT;
