-- 오라클 6일차 오라클 객체 Role
-- ====================== 3. ROLE
-- KH 계정
SELECT * FROM ROLE_SYS_PRIVS WHERE ROLE = 'CONNECT';
SELECT * FROM ROLE_SYS_PRIVS WHERE ROLE = 'VIEWRESOURCE';
-- ================= GRANT 실습
CREATE TABLE COFFEE
(
    PRODUCT_NAME VARCHAR2(20) PRIMARY KEY,
    PRICE NUMBER NOT NULL,
    COMPANY VARCHAR2(20) NOT NULL
);
INSERT INTO COFFEE VALUES('큐브라떼', 4300, 'MSG');
INSERT INTO COFFEE VALUES('허니자몽', 5300, 'STARBUCKS');
INSERT INTO COFFEE VALUES('아아', 2500, '맥심');
INSERT INTO COFFEE VALUES('아바라', 5500, '커피빈');
SELECT * FROM COFFEE;
COMMIT;