CREATE TABLE EMPLOYEE
(
    EMP_ID VARCHAR2 (3),
    EMP_NAME VARCHAR2 (20),
    EMP_NO CHAR (14),
    EMAIL VARCHAR2 (25),
    PHONE VARCHAR2 (12),
    DEPT_CODE CHAR (2),
    JOB_CODE CHAR (2),
    SAL_LEVEL CHAR (2),
    SALARY NUMBER,
    BONUS NUMBER,
    MANAGER_ID VARCHAR(3),
    HIRE_DATE DATE,
    ENT_DATE DATE,
    ENT_YN  CHAR(1)
);
DROP TABLE EMPLOYEE;
SELECT * FROM EMPLOYEE;

INSERT INTO EMPLOYEE(EMP_ID, EMP_NAME, EMP_NO, EMAIL, PHONE, DEPT_CODE, JOB_CODE, SAL_LEVEL, SALARY, BONUS, MANAGER_ID, HIRE_DATE, ENT_DATE, ENT_YN)
VALUES(200,'선동일', '621231-1985634', 'sun_di@kh.or.kr', 01099543625, 'D9', 'J1', 'S1', 8000000, '0.3', NULL,'13-02-06', NULL,'N');

-- 테이블 스키마 조회
DESC EMPLOYEE;