--------------------------------------------------------
--  파일이 생성됨 - 목요일-12월-07-2023   
--------------------------------------------------------
DROP TABLE "KH"."USER_CHECK" cascade constraints;
DROP TABLE "KH"."USER_PRIMARY_KEY" cascade constraints;
--------------------------------------------------------
--  DDL for Table USER_CHECK
--------------------------------------------------------

  CREATE TABLE "KH"."USER_CHECK" 
   (	"USER_NO" NUMBER, 
	"USER_ID" VARCHAR2(20 BYTE), 
	"USER_PWD" VARCHAR2(30 BYTE), 
	"USER_NAME" VARCHAR2(30 BYTE), 
	"USER_GENDER" VARCHAR2(10 BYTE), 
	"USER_PHONE" VARCHAR2(30 BYTE), 
	"USER_EMAIL" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USER_PRIMARY_KEY
--------------------------------------------------------

  CREATE TABLE "KH"."USER_PRIMARY_KEY" 
   (	"USER_NO" NUMBER, 
	"USER_ID" VARCHAR2(20 BYTE), 
	"USER_PWD" VARCHAR2(30 BYTE), 
	"USER_NAME" VARCHAR2(30 BYTE), 
	"USER_GENDER" VARCHAR2(10 BYTE), 
	"USER_PHONE" VARCHAR2(30 BYTE), 
	"USER_EMAIL" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into KH.USER_CHECK
SET DEFINE OFF;
REM INSERTING into KH.USER_PRIMARY_KEY
SET DEFINE OFF;
Insert into KH.USER_PRIMARY_KEY (USER_NO,USER_ID,USER_PWD,USER_NAME,USER_GENDER,USER_PHONE,USER_EMAIL) values (1,null,'pass01','일용자','남','01082827373','khuser01@kh.com');
Insert into KH.USER_PRIMARY_KEY (USER_NO,USER_ID,USER_PWD,USER_NAME,USER_GENDER,USER_PHONE,USER_EMAIL) values (1,'khuser01','pass01','일용자','남','01082827373','khuser01@kh.com');
--------------------------------------------------------
--  DDL for Index PK_USER_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "KH"."PK_USER_ID" ON "KH"."USER_CHECK" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007377
--------------------------------------------------------

  CREATE UNIQUE INDEX "KH"."SYS_C007377" ON "KH"."USER_CHECK" ("USER_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007308
--------------------------------------------------------

  CREATE UNIQUE INDEX "KH"."SYS_C007308" ON "KH"."USER_PRIMARY_KEY" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table USER_CHECK
--------------------------------------------------------

  ALTER TABLE "KH"."USER_CHECK" MODIFY ("USER_PWD" NOT NULL ENABLE);
  ALTER TABLE "KH"."USER_CHECK" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "KH"."USER_CHECK" ADD CHECK (USER_GENDER IN('M','F')) ENABLE;
  ALTER TABLE "KH"."USER_CHECK" ADD CONSTRAINT "PK_USER_ID" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KH"."USER_CHECK" ADD UNIQUE ("USER_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_PRIMARY_KEY
--------------------------------------------------------

  ALTER TABLE "KH"."USER_PRIMARY_KEY" MODIFY ("USER_PWD" NOT NULL ENABLE);
  ALTER TABLE "KH"."USER_PRIMARY_KEY" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "KH"."USER_PRIMARY_KEY" ADD UNIQUE ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
