-- 오라클 8일차, 오라클 인덱스 실습
-- 1. 100만개의 데이터를 넣을 테이블 생성
-- 2. 100만개 데이터 삽입(PL/SQL 반복문)
-- 3. 인덱스 설정 전 테스트
-- 4. 인덱스 설정
-- 5. 인덱스 설정 후 테스트


-- #1
CREATE TABLE KH_CUSTOMER_TBL
(
    USER_ID VARCHAR2(20),
    USER_PW VARCHAR2(30),
    USER_NAME VARCHAR2(30),
    USER_PHONE VARCHAR2(30),
    USER_ADDR VARCHAR2(500),
    REG_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    MOD_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_CUSTOMER_USERID
MINVALUE 1
MAXVALUE 999999999
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

-- #2
DECLARE
    V_USERID VARCHAR2(200);
BEGIN
    FOR N IN 1..1000000
    LOOP
        V_USERID := '1'||LPAD(SEQ_CUSTOMER_USERID.NEXTVAL, 9, '0');
        INSERT INTO KH_CUSTOMER_TBL
        VALUES(V_USERID, '0000', N||'용자', '010-0000-'||V_USERID,
        '서울시 중구 남대문로 '||N, DEFAULT, DEFAULT);
    END LOOP;
    COMMIT;
END;
/
-- INSERT 한 것을 지우고 싶어 -> DELETE FROM KH_CUSTOMER_TBL;
SELECT * FROM KH_CUSTOMER_TBL ORDER BY 1 DESC;
-- #3
-- 인덱스 걸기 전 실행시간 체크
EXPLAIN PLAN FOR
SELECT * FROM KH_CUSTOMER_TBL WHERE USER_NAME LIKE '22%용자';
-- 설명되었습니다.
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
-- 4394, 1초, TABLE ACCESS FULL

-- 인덱스 생성하기
CREATE INDEX IDX_CUSTOMER_USERNAME ON  KH_CUSTOMER_TBL(USER_NAME);
-- Index IDX_CUSTOMER_USERNAME이(가) 생성되었습니다.

-- 인덱스 건 후 실행시간 체크
EXPLAIN PLAN FOR
SELECT * FROM KH_CUSTOMER_TBL WHERE USER_NAME LIKE '22%용자';
-- 설명되었습니다.
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
-- 2904, 1초, INDEX RANGE SCAN





