-- DDL(CREATE, DROP, ALTER) - Data Definition Language
-- ALTER (오라클 객체)
-- ALTER를 이용한 제약조건 추가, 수정, 이름변경 해보기!
-- ALTER를 이용한 컬럼추가, 컬럼 수정, 컬럼명 수정, 컬럼 삭제, 테이블 변경 해보기!
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'SHOP_MEMBER';
SELECT * FROM USER_CONSTRAINTS WHERE OWNER = 'KH';
-- ** CONSTRAINT TYPE
-- P : PRIMARY KEY
-- R : FOREIGN KEY
-- C : CHECK OR NOT NULL
-- U : UNIQUE
-- 나중에 배울 서브쿼리를 이용한 테이블 복사
CREATE TABLE USER_FOREIGNKEY_COPY
AS SELECT * FROM USER_FOREIGNKEY;
-- 실행 후 복사된 테이블의 데이터 확인!!
SELECT * FROM USER_FOREIGNKEY_COPY;

-- 테이블에 컬럼 추가
ALTER TABLE USER_FOREIGNKEY_COPY
ADD USER_DATE DATE;
-- 테이블에 컬럼 삭제
ALTER TABLE USER_FOREIGNKEY_COPY
DROP COLUMN USER_DATE;
-- 실행 후 이(가) 변경되었습니다. 메시지 확인
DESC USER_FOREIGNKEY_COPY;
-- 테이블에 컬럼 수정(자료형 수정)
ALTER TABLE USER_FOREIGNKEY_COPY
MODIFY USER_DATE VARCHAR2(10);
-- 테이블에 컬럼명 수정
ALTER TABLE USER_FOREIGNKEY_COPY
RENAME COLUMN USER_DATE TO REG_DATE;
-- 테이블명 수정
ALTER TABLE USER_FOREIGNKEY_COPY
RENAME TO USER_ALTER_CHANGE;

RENAME USER_ALTER_CHANGE TO USER_FOREIGNKEY_COPY;

-- 제약조건 추가
-- 1. PK 제약조건 추가
ALTER TABLE SHOP_BUY
ADD CONSTRAINT PK_BUY_NO PRIMARY KEY(BUY_NO);
-- 2. FK 제약조건 추가
ALTER TABLE SHOP_BUY
ADD CONSTRAINT FK_USER_ID FOREIGN KEY(USER_ID) REFERENCES SHOP_MEMBER(USER_ID);
-- 3. DEFAULT,NOT NULL 제약조건 추가
ALTER TABLE SHOP_BUY
MODIFY REG_DATE DEFAULT '23/12/07';
-- 제약조건 삭제
-- 삭제할때는 제약조건명이 필요함.
-- 제약조건명 확인하는 방법 1. 테이블 클릭 > 제약조건 탭 2. SELECT문
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'SHOP_BUY';
ALTER TABLE SHOP_BUY
DROP CONSTRAINT SYS_C007433;
-- 제약조건 수정
-- > 삭제 후 추가
-- 제약조건 이름변경
ALTER TABLE SHOP_BUY
RENAME CONSTRAINT PK_BUY_NO TO PRIMARYKEY_BUYNO;
-- ** 제약조건 활성화/비활성화
ALTER TABLE SHOP_BUY
DISABLE CONSTRAINT FK_USER_ID;
ALTER TABLE SHOP_BUY
ENABLE CONSTRAINT FK_USER_ID;