--------------------------------------------------------
--  파일이 생성됨 - 목요일-12월-07-2023   
--------------------------------------------------------
DROP TABLE "KHUSER02"."SHOP_BUY" cascade constraints;
DROP TABLE "KHUSER02"."SHOP_MEMBER" cascade constraints;
DROP TABLE "KHUSER02"."USER_CHECK" cascade constraints;
DROP TABLE "KHUSER02"."USER_CONSTRAINT_NOTNULL" cascade constraints;
DROP TABLE "KHUSER02"."USER_CONSTRAINT_UNIQUE" cascade constraints;
DROP TABLE "KHUSER02"."USER_DEFAULT" cascade constraints;
DROP TABLE "KHUSER02"."USER_FOREIGNKEY" cascade constraints;
DROP TABLE "KHUSER02"."USER_FOREIGNKEY_COPY" cascade constraints;
DROP TABLE "KHUSER02"."USER_GRADE" cascade constraints;
DROP TABLE "KHUSER02"."USER_NO_CONSTRAINT" cascade constraints;
DROP TABLE "KHUSER02"."USER_PRIMARY_KEY" cascade constraints;
--------------------------------------------------------
--  DDL for Table SHOP_BUY
--------------------------------------------------------

  CREATE TABLE "KHUSER02"."SHOP_BUY" 
   (	"BUY_NO" NUMBER, 
	"USER_ID" VARCHAR2(30 BYTE), 
	"PRODUCT_NAME" VARCHAR2(20 BYTE), 
	"REG_DATE" DATE DEFAULT '23/12/07'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SHOP_MEMBER
--------------------------------------------------------

  CREATE TABLE "KHUSER02"."SHOP_MEMBER" 
   (	"USER_NO" NUMBER, 
	"USER_ID" VARCHAR2(20 BYTE), 
	"USER_PWD" VARCHAR2(30 BYTE), 
	"USER_NAME" VARCHAR2(30 BYTE), 
	"USER_GENDER" VARCHAR2(10 BYTE), 
	"USER_PHONE" VARCHAR2(30 BYTE), 
	"USER_EMAIL" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USER_CHECK
--------------------------------------------------------

  CREATE TABLE "KHUSER02"."USER_CHECK" 
   (	"USER_NO" NUMBER, 
	"USER_ID" VARCHAR2(20 BYTE), 
	"USER_PWD" VARCHAR2(30 BYTE), 
	"USER_NAME" VARCHAR2(30 BYTE), 
	"USER_GENDER" VARCHAR2(10 BYTE), 
	"USER_PHONE" VARCHAR2(30 BYTE), 
	"USER_EMAIL" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USER_CONSTRAINT_NOTNULL
--------------------------------------------------------

  CREATE TABLE "KHUSER02"."USER_CONSTRAINT_NOTNULL" 
   (	"USER_NO" NUMBER, 
	"USER_ID" VARCHAR2(20 BYTE), 
	"USER_PWD" VARCHAR2(30 BYTE), 
	"USER_NAME" VARCHAR2(30 BYTE), 
	"USER_GENDER" VARCHAR2(10 BYTE), 
	"USER_PHONE" VARCHAR2(30 BYTE), 
	"USER_EMAIL" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USER_CONSTRAINT_UNIQUE
--------------------------------------------------------

  CREATE TABLE "KHUSER02"."USER_CONSTRAINT_UNIQUE" 
   (	"USER_NO" NUMBER, 
	"USER_ID" VARCHAR2(20 BYTE), 
	"USER_PWD" VARCHAR2(30 BYTE), 
	"USER_NAME" VARCHAR2(30 BYTE), 
	"USER_GENDER" VARCHAR2(10 BYTE), 
	"USER_PHONE" VARCHAR2(30 BYTE), 
	"USER_EMAIL" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USER_DEFAULT
--------------------------------------------------------

  CREATE TABLE "KHUSER02"."USER_DEFAULT" 
   (	"USER_NO" NUMBER, 
	"USER_ID" VARCHAR2(20 BYTE), 
	"USER_PWD" VARCHAR2(30 BYTE), 
	"USER_NAME" VARCHAR2(30 BYTE), 
	"USER_GENDER" VARCHAR2(10 BYTE), 
	"USER_PHONE" VARCHAR2(30 BYTE), 
	"USER_EMAIL" VARCHAR2(50 BYTE), 
	"USER_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USER_FOREIGNKEY
--------------------------------------------------------

  CREATE TABLE "KHUSER02"."USER_FOREIGNKEY" 
   (	"USER_NO" NUMBER, 
	"USER_ID" VARCHAR2(20 BYTE), 
	"USER_PWD" VARCHAR2(30 BYTE), 
	"USER_NAME" VARCHAR2(30 BYTE), 
	"USER_GENDER" VARCHAR2(10 BYTE), 
	"USER_PHONE" VARCHAR2(30 BYTE), 
	"USER_EMAIL" VARCHAR2(50 BYTE), 
	"USER_DATE" DATE DEFAULT SYSDATE, 
	"GRADE_CODE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USER_FOREIGNKEY_COPY
--------------------------------------------------------

  CREATE TABLE "KHUSER02"."USER_FOREIGNKEY_COPY" 
   (	"USER_NO" NUMBER, 
	"USER_ID" VARCHAR2(20 BYTE), 
	"USER_PWD" VARCHAR2(30 BYTE), 
	"USER_NAME" VARCHAR2(30 BYTE), 
	"USER_GENDER" VARCHAR2(10 BYTE), 
	"USER_PHONE" VARCHAR2(30 BYTE), 
	"USER_EMAIL" VARCHAR2(50 BYTE), 
	"GRADE_CODE" NUMBER, 
	"REG_DATE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USER_GRADE
--------------------------------------------------------

  CREATE TABLE "KHUSER02"."USER_GRADE" 
   (	"GRADE_CODE" NUMBER, 
	"GRADE_NAME" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USER_NO_CONSTRAINT
--------------------------------------------------------

  CREATE TABLE "KHUSER02"."USER_NO_CONSTRAINT" 
   (	"USER_NO" NUMBER, 
	"USER_ID" VARCHAR2(20 BYTE), 
	"USER_PWD" VARCHAR2(30 BYTE), 
	"USER_NAME" VARCHAR2(30 BYTE), 
	"USER_GENDER" VARCHAR2(10 BYTE), 
	"USER_PHONE" VARCHAR2(30 BYTE), 
	"USER_EMAIL" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USER_PRIMARY_KEY
--------------------------------------------------------

  CREATE TABLE "KHUSER02"."USER_PRIMARY_KEY" 
   (	"USER_NO" NUMBER, 
	"USER_ID" VARCHAR2(20 BYTE), 
	"USER_PWD" VARCHAR2(30 BYTE), 
	"USER_NAME" VARCHAR2(30 BYTE), 
	"USER_GENDER" VARCHAR2(10 BYTE), 
	"USER_PHONE" VARCHAR2(30 BYTE), 
	"USER_EMAIL" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into KHUSER02.SHOP_BUY
SET DEFINE OFF;
Insert into KHUSER02.SHOP_BUY (BUY_NO,USER_ID,PRODUCT_NAME,REG_DATE) values (1,'KHUSER02user01','농구화',to_date('23/12/07','RR/MM/DD'));
Insert into KHUSER02.SHOP_BUY (BUY_NO,USER_ID,PRODUCT_NAME,REG_DATE) values (2,'KHUSER02user02','축구화',to_date('23/12/07','RR/MM/DD'));
Insert into KHUSER02.SHOP_BUY (BUY_NO,USER_ID,PRODUCT_NAME,REG_DATE) values (3,'KHUSER02user03','배구화',to_date('23/12/07','RR/MM/DD'));
REM INSERTING into KHUSER02.SHOP_MEMBER
SET DEFINE OFF;
Insert into KHUSER02.SHOP_MEMBER (USER_NO,USER_ID,USER_PWD,USER_NAME,USER_GENDER,USER_PHONE,USER_EMAIL) values (1,'KHUSER02user01','pass01','일용자','M','01082893933','KHUSER02user01@naver.com');
Insert into KHUSER02.SHOP_MEMBER (USER_NO,USER_ID,USER_PWD,USER_NAME,USER_GENDER,USER_PHONE,USER_EMAIL) values (2,'KHUSER02user02','pass02','일용자','M','01082893933','KHUSER02user02@naver.com');
Insert into KHUSER02.SHOP_MEMBER (USER_NO,USER_ID,USER_PWD,USER_NAME,USER_GENDER,USER_PHONE,USER_EMAIL) values (3,'KHUSER02user03','pass03','일용자','M','01082893933','KHUSER02user03@naver.com');
REM INSERTING into KHUSER02.USER_CHECK
SET DEFINE OFF;
Insert into KHUSER02.USER_CHECK (USER_NO,USER_ID,USER_PWD,USER_NAME,USER_GENDER,USER_PHONE,USER_EMAIL) values (1,'KHUSER02user01','pass01','일용자','M','01082827373','KHUSER02user01@KHUSER02.com');
REM INSERTING into KHUSER02.USER_CONSTRAINT_NOTNULL
SET DEFINE OFF;
REM INSERTING into KHUSER02.USER_CONSTRAINT_UNIQUE
SET DEFINE OFF;
Insert into KHUSER02.USER_CONSTRAINT_UNIQUE (USER_NO,USER_ID,USER_PWD,USER_NAME,USER_GENDER,USER_PHONE,USER_EMAIL) values (1,null,'pass01','일용자','남','01082827373','KHUSER02user01@KHUSER02.com');
Insert into KHUSER02.USER_CONSTRAINT_UNIQUE (USER_NO,USER_ID,USER_PWD,USER_NAME,USER_GENDER,USER_PHONE,USER_EMAIL) values (1,'KHUSER02user01','pass01','일용자','남','01082827373','KHUSER02user01@KHUSER02.com');
REM INSERTING into KHUSER02.USER_DEFAULT
SET DEFINE OFF;
Insert into KHUSER02.USER_DEFAULT (USER_NO,USER_ID,USER_PWD,USER_NAME,USER_GENDER,USER_PHONE,USER_EMAIL,USER_DATE) values (1,'KHUSER02user01','pass01','일용자','M','01082827373','KHUSER02user01@KHUSER02.com',to_date('23/12/07','RR/MM/DD'));
Insert into KHUSER02.USER_DEFAULT (USER_NO,USER_ID,USER_PWD,USER_NAME,USER_GENDER,USER_PHONE,USER_EMAIL,USER_DATE) values (2,'KHUSER02user02','pass02','이용자','M','01082827373','KHUSER02user02@KHUSER02.com',to_date('23/12/14','RR/MM/DD'));
Insert into KHUSER02.USER_DEFAULT (USER_NO,USER_ID,USER_PWD,USER_NAME,USER_GENDER,USER_PHONE,USER_EMAIL,USER_DATE) values (3,'KHUSER02user03','pass03','삼용자','M','01082827373','KHUSER02user03@KHUSER02.com',to_date('23/12/07','RR/MM/DD'));
REM INSERTING into KHUSER02.USER_FOREIGNKEY
SET DEFINE OFF;
Insert into KHUSER02.USER_FOREIGNKEY (USER_NO,USER_ID,USER_PWD,USER_NAME,USER_GENDER,USER_PHONE,USER_EMAIL,USER_DATE,GRADE_CODE) values (1,'KHUSER02user01','pass01','일용자','M','01082827373','KHUSER02user01@KHUSER02.com',to_date('23/12/07','RR/MM/DD'),null);
Insert into KHUSER02.USER_FOREIGNKEY (USER_NO,USER_ID,USER_PWD,USER_NAME,USER_GENDER,USER_PHONE,USER_EMAIL,USER_DATE,GRADE_CODE) values (2,'KHUSER02user02','pass02','이용자','M','01082827373','KHUSER02user02@KHUSER02.com',to_date('23/12/07','RR/MM/DD'),20);
REM INSERTING into KHUSER02.USER_FOREIGNKEY_COPY
SET DEFINE OFF;
Insert into KHUSER02.USER_FOREIGNKEY_COPY (USER_NO,USER_ID,USER_PWD,USER_NAME,USER_GENDER,USER_PHONE,USER_EMAIL,GRADE_CODE,REG_DATE) values (1,'KHUSER02user01','pass01','일용자','M','01082827373','KHUSER02user01@KHUSER02.com',null,null);
Insert into KHUSER02.USER_FOREIGNKEY_COPY (USER_NO,USER_ID,USER_PWD,USER_NAME,USER_GENDER,USER_PHONE,USER_EMAIL,GRADE_CODE,REG_DATE) values (2,'KHUSER02user02','pass02','이용자','M','01082827373','KHUSER02user02@KHUSER02.com',20,null);
REM INSERTING into KHUSER02.USER_GRADE
SET DEFINE OFF;
Insert into KHUSER02.USER_GRADE (GRADE_CODE,GRADE_NAME) values (20,'우수회원');
Insert into KHUSER02.USER_GRADE (GRADE_CODE,GRADE_NAME) values (30,'특별회원');
REM INSERTING into KHUSER02.USER_NO_CONSTRAINT
SET DEFINE OFF;
Insert into KHUSER02.USER_NO_CONSTRAINT (USER_NO,USER_ID,USER_PWD,USER_NAME,USER_GENDER,USER_PHONE,USER_EMAIL) values (1,'KHUSER02user01','pass01','일용자','남','01082827373','KHUSER02user01@KHUSER02.com');
Insert into KHUSER02.USER_NO_CONSTRAINT (USER_NO,USER_ID,USER_PWD,USER_NAME,USER_GENDER,USER_PHONE,USER_EMAIL) values (1,null,'pass01','일용자','남','01082827373','KHUSER02user01@KHUSER02.com');
Insert into KHUSER02.USER_NO_CONSTRAINT (USER_NO,USER_ID,USER_PWD,USER_NAME,USER_GENDER,USER_PHONE,USER_EMAIL) values (1,null,'pass01','일용자','남','01082827373','KHUSER02user01@KHUSER02.com');
REM INSERTING into KHUSER02.USER_PRIMARY_KEY
SET DEFINE OFF;
Insert into KHUSER02.USER_PRIMARY_KEY (USER_NO,USER_ID,USER_PWD,USER_NAME,USER_GENDER,USER_PHONE,USER_EMAIL) values (1,'KHUSER02user01','pass01','일용자','남','01082827373','KHUSER02user01@KHUSER02.com');
--------------------------------------------------------
--  DDL for Index PK_BUY_NO
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHUSER02"."PK_BUY_NO" ON "KHUSER02"."SHOP_BUY" ("BUY_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007431
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHUSER02"."SYS_C007431" ON "KHUSER02"."SHOP_MEMBER" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007432
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHUSER02"."SYS_C007432" ON "KHUSER02"."SHOP_MEMBER" ("USER_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_USER_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHUSER02"."PK_USER_ID" ON "KHUSER02"."USER_CHECK" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007408
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHUSER02"."SYS_C007408" ON "KHUSER02"."USER_CHECK" ("USER_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007399
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHUSER02"."SYS_C007399" ON "KHUSER02"."USER_CONSTRAINT_UNIQUE" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007418
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHUSER02"."SYS_C007418" ON "KHUSER02"."USER_DEFAULT" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007419
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHUSER02"."SYS_C007419" ON "KHUSER02"."USER_DEFAULT" ("USER_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007444
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHUSER02"."SYS_C007444" ON "KHUSER02"."USER_FOREIGNKEY" ("USER_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007445
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHUSER02"."SYS_C007445" ON "KHUSER02"."USER_FOREIGNKEY" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007421
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHUSER02"."SYS_C007421" ON "KHUSER02"."USER_GRADE" ("GRADE_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007402
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHUSER02"."SYS_C007402" ON "KHUSER02"."USER_PRIMARY_KEY" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007403
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHUSER02"."SYS_C007403" ON "KHUSER02"."USER_PRIMARY_KEY" ("USER_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SHOP_BUY
--------------------------------------------------------

  ALTER TABLE "KHUSER02"."SHOP_BUY" ADD CONSTRAINT "PRIMARYKEY_BUYNO" PRIMARY KEY ("BUY_NO")
  USING INDEX (CREATE UNIQUE INDEX "KHUSER02"."PK_BUY_NO" ON "KHUSER02"."SHOP_BUY" ("BUY_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table SHOP_MEMBER
--------------------------------------------------------

  ALTER TABLE "KHUSER02"."SHOP_MEMBER" MODIFY ("USER_PWD" NOT NULL ENABLE);
  ALTER TABLE "KHUSER02"."SHOP_MEMBER" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "KHUSER02"."SHOP_MEMBER" ADD CHECK (USER_GENDER IN('M','F')) ENABLE;
  ALTER TABLE "KHUSER02"."SHOP_MEMBER" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KHUSER02"."SHOP_MEMBER" ADD UNIQUE ("USER_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_CHECK
--------------------------------------------------------

  ALTER TABLE "KHUSER02"."USER_CHECK" MODIFY ("USER_PWD" NOT NULL ENABLE);
  ALTER TABLE "KHUSER02"."USER_CHECK" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "KHUSER02"."USER_CHECK" ADD CHECK (USER_GENDER IN('M','F')) ENABLE;
  ALTER TABLE "KHUSER02"."USER_CHECK" ADD CONSTRAINT "PK_USER_ID" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KHUSER02"."USER_CHECK" ADD UNIQUE ("USER_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_CONSTRAINT_NOTNULL
--------------------------------------------------------

  ALTER TABLE "KHUSER02"."USER_CONSTRAINT_NOTNULL" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "KHUSER02"."USER_CONSTRAINT_NOTNULL" MODIFY ("USER_PWD" NOT NULL ENABLE);
  ALTER TABLE "KHUSER02"."USER_CONSTRAINT_NOTNULL" MODIFY ("USER_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USER_CONSTRAINT_UNIQUE
--------------------------------------------------------

  ALTER TABLE "KHUSER02"."USER_CONSTRAINT_UNIQUE" MODIFY ("USER_PWD" NOT NULL ENABLE);
  ALTER TABLE "KHUSER02"."USER_CONSTRAINT_UNIQUE" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "KHUSER02"."USER_CONSTRAINT_UNIQUE" ADD UNIQUE ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_DEFAULT
--------------------------------------------------------

  ALTER TABLE "KHUSER02"."USER_DEFAULT" MODIFY ("USER_PWD" NOT NULL ENABLE);
  ALTER TABLE "KHUSER02"."USER_DEFAULT" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "KHUSER02"."USER_DEFAULT" ADD CHECK (USER_GENDER IN('M','F')) ENABLE;
  ALTER TABLE "KHUSER02"."USER_DEFAULT" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KHUSER02"."USER_DEFAULT" ADD UNIQUE ("USER_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_FOREIGNKEY
--------------------------------------------------------

  ALTER TABLE "KHUSER02"."USER_FOREIGNKEY" MODIFY ("USER_PWD" NOT NULL ENABLE);
  ALTER TABLE "KHUSER02"."USER_FOREIGNKEY" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "KHUSER02"."USER_FOREIGNKEY" ADD CHECK (USER_GENDER IN('M','F')) ENABLE;
  ALTER TABLE "KHUSER02"."USER_FOREIGNKEY" ADD PRIMARY KEY ("USER_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KHUSER02"."USER_FOREIGNKEY" ADD UNIQUE ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_FOREIGNKEY_COPY
--------------------------------------------------------

  ALTER TABLE "KHUSER02"."USER_FOREIGNKEY_COPY" MODIFY ("USER_PWD" NOT NULL ENABLE);
  ALTER TABLE "KHUSER02"."USER_FOREIGNKEY_COPY" MODIFY ("USER_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USER_GRADE
--------------------------------------------------------

  ALTER TABLE "KHUSER02"."USER_GRADE" MODIFY ("GRADE_NAME" NOT NULL ENABLE);
  ALTER TABLE "KHUSER02"."USER_GRADE" ADD PRIMARY KEY ("GRADE_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_PRIMARY_KEY
--------------------------------------------------------

  ALTER TABLE "KHUSER02"."USER_PRIMARY_KEY" MODIFY ("USER_PWD" NOT NULL ENABLE);
  ALTER TABLE "KHUSER02"."USER_PRIMARY_KEY" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "KHUSER02"."USER_PRIMARY_KEY" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KHUSER02"."USER_PRIMARY_KEY" ADD UNIQUE ("USER_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SHOP_BUY
--------------------------------------------------------

  ALTER TABLE "KHUSER02"."SHOP_BUY" ADD CONSTRAINT "FK_USER_ID" FOREIGN KEY ("USER_ID")
	  REFERENCES "KHUSER02"."SHOP_MEMBER" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USER_FOREIGNKEY
--------------------------------------------------------

  ALTER TABLE "KHUSER02"."USER_FOREIGNKEY" ADD FOREIGN KEY ("GRADE_CODE")
	  REFERENCES "KHUSER02"."USER_GRADE" ("GRADE_CODE") ON DELETE SET NULL ENABLE;
