-- 계정생성 삭제, 테이블생성 삭제 DDL
-- 계정권한 DCL
-- 데이터 조회 DQL
-- 데이터 삽입/삭제, 수정 DML
-- 커밋 및 롤백 TCL
SHOW USER;
-- 테이블 생성
CREATE TABLE MEMBER_TBL
(
    MEMBER_NO NUMBER,
    MEMBER_ID VARCHAR2 (20),
    MEMBER_NAME VARCHAR2 (30),
    MEMBER_EMAIL VARCHAR2 (50)
);
-- 데이터 삭제
DROP TABLE MEMBER_TBL;
-- 데이터 조회 DML(DQL)
SELECT * FROM MEMBER_TBL;
-- 데이터 삽입
INSERT INTO MEMBER_TBL(MEMBER_NO, MEMBER_ID, MEMBER_NAME, MEMBER_EMAIL)
VALUES(1, 'KHUSER01', '일용자', 'khuser01@kh.com');
INSERT INTO MEMBER_TBL(MEMBER_NO, MEMBER_ID, MEMBER_NAME, MEMBER_EMAIL)
VALUES(2, 'KHUSER02', '이용자', 'khuser02@kh.com');
INSERT INTO MEMBER_TBL(MEMBER_NO, MEMBER_ID, MEMBER_NAME, MEMBER_EMAIL)
VALUES(3, 'KHUSER03', '삼용자', 'khuser03@kh.com');
INSERT INTO MEMBER_TBL(MEMBER_NO, MEMBER_ID, MEMBER_NAME, MEMBER_EMAIL)
VALUES(4, 'KHUSER04', '사용자', 'khuser04@kh.com');
-- 데이터 수정
UPDATE MEMBER_TBL SET MEMBER_NAME = '십일용자' WHERE MEMBER_NO = 1;
-- 데이터 삭제 DELETE는 WHERE로 조건삭제를 해야 한다.
DELETE FROM MEMBER_TBL WHERE MEMBER_NO = 1;
-- 롤백 명령어 TCL (F12)
ROLLBACK;
-- 최종 저장 TCL (F11)
COMMIT;